
package com.java.polr.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileTransferImplService", targetNamespace = "http://webservice.polr.java.com/", wsdlLocation = "http://localhost:8888/fileServer/fileService?wsdl")
public class FileTransferImplService
    extends Service
{

    private final static URL FILETRANSFERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILETRANSFERIMPLSERVICE_EXCEPTION;
    private final static QName FILETRANSFERIMPLSERVICE_QNAME = new QName("http://webservice.polr.java.com/", "FileTransferImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/fileServer/fileService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILETRANSFERIMPLSERVICE_WSDL_LOCATION = url;
        FILETRANSFERIMPLSERVICE_EXCEPTION = e;
    }

    public FileTransferImplService() {
        super(__getWsdlLocation(), FILETRANSFERIMPLSERVICE_QNAME);
    }

    public FileTransferImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILETRANSFERIMPLSERVICE_QNAME, features);
    }

    public FileTransferImplService(URL wsdlLocation) {
        super(wsdlLocation, FILETRANSFERIMPLSERVICE_QNAME);
    }

    public FileTransferImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILETRANSFERIMPLSERVICE_QNAME, features);
    }

    public FileTransferImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileTransferImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileTransferImpl
     */
    @WebEndpoint(name = "FileTransferImplPort")
    public FileTransferImpl getFileTransferImplPort() {
        return super.getPort(new QName("http://webservice.polr.java.com/", "FileTransferImplPort"), FileTransferImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileTransferImpl
     */
    @WebEndpoint(name = "FileTransferImplPort")
    public FileTransferImpl getFileTransferImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.polr.java.com/", "FileTransferImplPort"), FileTransferImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILETRANSFERIMPLSERVICE_EXCEPTION!= null) {
            throw FILETRANSFERIMPLSERVICE_EXCEPTION;
        }
        return FILETRANSFERIMPLSERVICE_WSDL_LOCATION;
    }

}
